// Package hooks provides hook installation for AI CLI tools.
package hooks

import (
	"fmt"
	"os"
	"path/filepath"
)

// Aider configuration files
const aiderConventionsMD = `# MUR Patterns

This file is auto-generated by mur-core to inject learned patterns.

## Usage

Patterns are injected based on the current context (language, project type).

To refresh patterns, run:
` + "```bash\nmur inject --tool aider > .aider/conventions.md\n```" + `

## Patterns

<!-- MUR_PATTERNS_START -->
Run 'mur inject --tool aider' to populate this section.
<!-- MUR_PATTERNS_END -->
`

const aiderConfYaml = `# Aider configuration with mur integration
# See: https://aider.chat/docs/config.html

# Enable conventions file
read:
  - .aider/conventions.md

# Auto-commits (optional)
auto-commits: true
`

// AiderInstalled checks if Aider is installed.
func AiderInstalled() bool {
	// Check if aider command exists
	_, err := findBinary("aider")
	return err == nil
}

func findBinary(name string) (string, error) {
	// Try to find in common locations
	home, _ := os.UserHomeDir()
	paths := []string{
		filepath.Join(home, ".local", "bin", name),
		filepath.Join("/usr/local/bin", name),
		filepath.Join("/opt/homebrew/bin", name),
	}

	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
	}

	return "", fmt.Errorf("%s not found", name)
}

// InstallAiderHooks installs mur integration for Aider.
func InstallAiderHooks() error {
	// Aider uses conventions files in the project directory
	// We'll create a template and instructions

	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot determine home directory: %w", err)
	}

	// Create global .aider directory
	aiderDir := filepath.Join(home, ".aider")
	if err := os.MkdirAll(aiderDir, 0755); err != nil {
		return fmt.Errorf("cannot create .aider directory: %w", err)
	}

	// Write conventions template
	conventionsPath := filepath.Join(aiderDir, "conventions.md")
	if err := os.WriteFile(conventionsPath, []byte(aiderConventionsMD), 0644); err != nil {
		return fmt.Errorf("cannot write conventions.md: %w", err)
	}

	// Write aider.conf.yml template
	confPath := filepath.Join(aiderDir, "aider.conf.yml")
	if err := os.WriteFile(confPath, []byte(aiderConfYaml), 0644); err != nil {
		return fmt.Errorf("cannot write aider.conf.yml: %w", err)
	}

	fmt.Printf("✓ Installed Aider integration at %s\n", aiderDir)
	fmt.Println("  + conventions.md template")
	fmt.Println("  + aider.conf.yml template")
	fmt.Println()
	fmt.Println("To use in a project:")
	fmt.Println("  1. Copy ~/.aider to your project root")
	fmt.Println("  2. Run: mur inject --tool aider > .aider/conventions.md")
	fmt.Println("  3. Start aider with: aider --config .aider/aider.conf.yml")

	return nil
}
