#!/usr/bin/env bash
# inject_claude_md.sh — Inject learned rules into a project's CLAUDE.md
# Usage:
#   ./scripts/inject_claude_md.sh --target ~/Projects/myapp
#   ./scripts/inject_claude_md.sh --target ~/Projects/myapp --contexts devops,backend
#   ./scripts/inject_claude_md.sh --target ~/Projects/myapp --project twdd-api
#   ./scripts/inject_claude_md.sh --target ~/Projects/myapp --dry-run
#   ./scripts/inject_claude_md.sh --target ~/Projects/myapp --remove
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LEARNED_DIR="$SKILL_DIR/learned"

# --- Markers ---
START_MARKER="<!-- LEARNED RULES (auto-generated by claude-code-learner) -->"
END_MARKER="<!-- END LEARNED RULES -->"

# --- Defaults ---
TARGET_DIR=""
DRY_RUN=false
REMOVE=false
CONTEXTS=""
PROJECT=""

# --- Parse args ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)    TARGET_DIR="$2"; shift 2 ;;
    --dry-run)   DRY_RUN=true; shift ;;
    --remove)    REMOVE=true; shift ;;
    --contexts)  CONTEXTS="$2"; shift 2 ;;
    --project)   PROJECT="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: inject_claude_md.sh --target /path/to/repo [--contexts D1,D2] [--project P] [--dry-run] [--remove]"
      echo ""
      echo "Inject high-confidence learned rules into a project's CLAUDE.md."
      echo ""
      echo "Options:"
      echo "  --target DIR          Target repository directory (required)"
      echo "  --contexts DOMAINS    Comma-separated domains (e.g. devops,backend). Always includes _global."
      echo "  --project PROJECT     Include project-specific patterns"
      echo "  --dry-run             Show what would be injected without writing"
      echo "  --remove              Remove injected learned rules section"
      echo "  -h, --help            Show this help"
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# --- Validate ---
if [[ -z "$TARGET_DIR" ]]; then
  echo "Error: --target is required." >&2; exit 1
fi
TARGET_DIR="${TARGET_DIR/#\~/$HOME}"
if [[ ! -d "$TARGET_DIR" ]]; then
  echo "Error: Directory not found: $TARGET_DIR" >&2; exit 1
fi

CLAUDE_MD="$TARGET_DIR/CLAUDE.md"

# --- Remove mode ---
if [[ "$REMOVE" == "true" ]]; then
  if [[ ! -f "$CLAUDE_MD" ]]; then
    echo "No CLAUDE.md found at $CLAUDE_MD" >&2; exit 0
  fi
  if ! grep -q "$START_MARKER" "$CLAUDE_MD" 2>/dev/null; then
    echo "No learned rules section found in $CLAUDE_MD" >&2; exit 0
  fi
  if [[ "$DRY_RUN" == "true" ]]; then
    echo "[DRY RUN] Would remove learned rules section from $CLAUDE_MD" >&2; exit 0
  fi
  python3 -c "
with open('$CLAUDE_MD', 'r') as f:
    lines = f.readlines()
out = []
skip = False
for line in lines:
    if '$START_MARKER' in line:
        skip = True
        continue
    if '$END_MARKER' in line:
        skip = False
        continue
    if not skip:
        out.append(line)
while out and out[-1].strip() == '':
    out.pop()
out.append('\n')
with open('$CLAUDE_MD', 'w') as f:
    f.writelines(out)
"
  echo "✅ Removed learned rules section from $CLAUDE_MD" >&2
  exit 0
fi

# --- Build search paths ---
SEARCH_DIRS=()
# Always include _global
SEARCH_DIRS+=("$LEARNED_DIR/_global")

if [[ -n "$CONTEXTS" ]]; then
  IFS=',' read -ra CTX_ARRAY <<< "$CONTEXTS"
  for ctx in "${CTX_ARRAY[@]}"; do
    ctx=$(echo "$ctx" | tr -d ' ')
    [[ "$ctx" == "_global" ]] && continue  # already added
    if [[ -d "$LEARNED_DIR/$ctx" ]]; then
      SEARCH_DIRS+=("$LEARNED_DIR/$ctx")
    fi
  done
else
  # If no contexts specified, search all domains
  for d in "$LEARNED_DIR"/*/; do
    [[ -d "$d" ]] && SEARCH_DIRS+=("$d")
  done
fi

# Include project-specific if specified
if [[ -n "$PROJECT" && -d "$LEARNED_DIR/projects/$PROJECT" ]]; then
  SEARCH_DIRS+=("$LEARNED_DIR/projects/$PROJECT")
fi

# --- Collect HIGH confidence patterns from search dirs ---
HIGH_PATTERNS=()
for dir in "${SEARCH_DIRS[@]}"; do
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    CONF=$(grep '^confidence:' "$f" 2>/dev/null | sed 's/confidence: *//' || echo "")
    if [[ "$CONF" == "HIGH" ]]; then
      HIGH_PATTERNS+=("$f")
    fi
  done < <(find "$dir" -name "*.md" -not -name ".gitkeep" -not -name "archived-*" -not -name "skill-*" 2>/dev/null | sort)
done

if [[ ${#HIGH_PATTERNS[@]} -eq 0 ]]; then
  echo "📭 No HIGH confidence patterns found. Nothing to inject." >&2; exit 0
fi

# --- Build the injection block ---
INJECTION=""
INJECTION+="$START_MARKER"$'\n'
INJECTION+="## Learned Rules"$'\n'
INJECTION+=""$'\n'

for f in "${HIGH_PATTERNS[@]}"; do
  P_NAME=$(grep '^name:' "$f" | sed 's/name: *//')
  P_TITLE=$(grep '^# ' "$f" | head -1 | sed 's/^# //')
  P_DOM=$(grep '^domain:' "$f" | sed 's/domain: *//' || echo "")
  P_DESC=$(sed -n '/^## Problem/,/^##/{/^##/!p}' "$f" | sed '/^$/d' | head -1)
  [[ -z "$P_DESC" ]] && P_DESC="$P_TITLE"
  INJECTION+="- **${P_NAME}** [${P_DOM}]: ${P_DESC}"$'\n'
done

INJECTION+="$END_MARKER"$'\n'

# --- Dry run ---
if [[ "$DRY_RUN" == "true" ]]; then
  echo "🔍 [DRY RUN] Would inject ${#HIGH_PATTERNS[@]} rule(s) into $CLAUDE_MD:" >&2
  echo "" >&2
  echo "$INJECTION"
  exit 0
fi

# --- Inject into CLAUDE.md ---
if [[ ! -f "$CLAUDE_MD" ]]; then
  echo "$INJECTION" > "$CLAUDE_MD"
  echo "✅ Created $CLAUDE_MD with ${#HIGH_PATTERNS[@]} learned rule(s)." >&2
  exit 0
fi

if grep -q "$START_MARKER" "$CLAUDE_MD" 2>/dev/null; then
  python3 -c "
start_marker = '$START_MARKER'
end_marker = '$END_MARKER'
injection = '''$INJECTION'''
with open('$CLAUDE_MD', 'r') as f:
    content = f.read()
start_idx = content.find(start_marker)
end_idx = content.find(end_marker)
if start_idx >= 0 and end_idx >= 0:
    end_idx += len(end_marker)
    if end_idx < len(content) and content[end_idx] == '\n':
        end_idx += 1
    content = content[:start_idx] + injection + content[end_idx:]
with open('$CLAUDE_MD', 'w') as f:
    f.write(content)
"
  echo "✅ Updated learned rules in $CLAUDE_MD (${#HIGH_PATTERNS[@]} rule(s))." >&2
else
  echo "" >> "$CLAUDE_MD"
  echo "$INJECTION" >> "$CLAUDE_MD"
  echo "✅ Appended ${#HIGH_PATTERNS[@]} learned rule(s) to $CLAUDE_MD." >&2
fi
